### ISSUE TITLE
Why reimplement existing things?

### ISSUE THREAD

**Issue by OrfeasLitos** [bcoin-org/bmocha#2]
Many of the `b*` repos implement things that already exist and are actively developed by other teams, while there are things like SPV or multisig that are not 100% covered in the `bcoin` implementation. I hope I'm not being too nosy, but I would like to know if there is a reason why a lot of energy is spent on what seemingly is a duplication of effort, while there are unresolved issues with the core bcoin library.

**Comment by dionyziz** [comment]
I second this. Not only are the duplicate implementations wasted effort, but, according to our experience developing with bcoin (which can be assessed by @OrfeasLitos, @gtklocker, and me), there are often bugs in the re-implementations of things. bmocha is only one example.

Last but not least, even if these duplicate implementations are bug-free, it takes precious maintenance effort to backport new features from the other libraries who have dedicated maintainers and expert knowledge in their respective domain. Are we suffering a [not invented here syndrome](https://en.wikipedia.org/wiki/Not_invented_here)?

**Comment by gtklocker** [comment]
I think the only reasonable explanation is that the bcoin team wants to minimize the attack surface area from dependencies they don't control.

**Comment by chjj** [comment]
mocha pulls in a ton of dependencies. The reason this module was created was in response to the most recent package attack on event-stream. bcoin will eventually not have any 3rd-party dependencies (yes, even dev dependencies).

Closing.

**Comment by braydonf** [comment]
Yep, mocha has _many_ dependencies, most of which haven't been maintained for over 1 year, and many over 2+ years, and has become overly complicated. For more information see https://github.com/bcoin-org/bcoin/issues/619
