### ISSUE TITLE
Recursive with sub-directories and file matching

### ISSUE THREAD

**Issue by braydonf** [bcoin-org/bmocha#4]
**Versions**
bmocha v1.0.1

**Expected**

Given this directory and file structure:
```
./test/util/util.js
./test/bar/baz-test.js
./test/bar/qux-test.js
./test/foo-test.js
```

For this command:
```sh
$ bmocha --recursive "./test/**/*-test.js"`
```

To run these files:
```
./test/bar/baz-test.js
./test/bar/qux-test.js
./test/foo-test.js
```

**Actual**
```sh
File not found: test/**/*-test.js
```

**Alternatives**

It could be possible to run:
```
$ bmocha --recursive ./test/
```
However then _all_ of the files are loaded, including the util files.

Another option:

```
$ bmocha --recursive ./test/*-test.js
```

Will only match, or recurse, anything that matches the initial *-test.js file list, which won't be the `bar` directory, and thus will only run `./test/foo-test.js`

**Proposal**

_Option A)_

Introduce two new arguments `--directory` and `--files`, example usage:
```
$ bmocha --recursive --directory="./test/" --files="*-test.js"
```
Files could use a regexp for matching, or more shorthand `*` syntax.

_Option B)_

Use the globstar pattern matching, as would match mocha behavior more similarly:
```
$ bmocha --recursive "./test/**/*-test.js"`
```

**Comment by tynes** [comment]
I like option B more, its less typing and more similar to mocha

**Comment by boymanjor** [comment]
I am also in favor of option B.
