### ISSUE TITLE
Headless Browser: Cannot locate bpkg or browserify

### ISSUE THREAD

**Issue by tynes** [bcoin-org/bmocha#6]
OSX

```bash
$ npm --version
6.9.0

$ node --version
v11.11.0
```

I'd like to test browser functionality of `bcoin` and `hsd`.  After install `browserify` and `bpkg` globally, running this command for `bcoin#master` (which doesn't yet have a 2.x.x version of `bmocha`) throws an error.
```bash
$ ./node_modules/.bin/bmocha -H --reporter spec test/*.js
Error: Browserify not installed!
...
```
According to the docs, it should work on a globally installed `browserify`.

After updating `bmocha` on `bcoin`, digging into `bmocha@2.1.0` to determine
why this is happening, I found the list of `node_modules` paths are generated here:
https://github.com/bcoin-org/bmocha/blob/fa388102f751f6d2debaea90308d53a67c71d78c/lib/require.js#L108

Logging those paths, none of them include the directory in which `npm` installed `browserify` and `bpkg`.

```bash
$ which bpkg
/usr/local/bin/bpkg

$ which browserify
/usr/local/bin/browserify
```
Looking at where `npm` installs things globally:
```bash
$ npm list -g | head -n 1
/usr/local/lib
```

I can't find any changelogs that refer to changing the location of the global installs, but did find this: https://docs.npmjs.com/files/folders

> The prefix config defaults to the location where node is installed. On most systems, this is /usr/local. On Windows, it’s %AppData%\npm. On Unix systems, it’s one level up, since node is typically installed at {prefix}/bin/node rather than {prefix}/node.exe. 
> When the global flag is set, npm installs things into this prefix. When it is not set, it uses the root of the current package, or the current working directory if not in a package already.

This corresponds to my local install of Node.js
```
$ which node
/usr/local/bin/node
```

This means that the docs here are not fully correct for OSX at least:
https://github.com/bcoin-org/bmocha#headless-chrome--browser-support

**Comment by tynes** [comment]
This problem can be mitigated by including `bpkg` as a `devDependency` for `bcoin` and `hsd`

**Comment by chjj** [comment]
@tynes, a global install usually puts modules in `$PREFIX/lib/node` or `$PREFIX/lib/node_modules`. See: https://github.com/bcoin-org/bmocha/blob/master/lib/require.js#L133

If your install path for node is `/usr/local/bin/node`, that should resolve to `/usr/local/lib/node_modules`. Where does `$ readlink /usr/local/bin/bpkg` resolve to for you?

**Comment by tynes** [comment]
```bash
$ readlink /usr/local/bin/bpkg
../lib/node_modules/bpkg/bin/bpkg
```

I did a fresh install of hsd, updated the `package.json` with the line:
```
    "bmocha": "https://github.com/bcoin-org/bmocha.git"
```
and then logged the paths at the link you posted above.
```bash
$ ./node_modules/.bin/bmocha -H test/mnemonic-test.js
[ '/private/tmp/hsd/node_modules',
  '/private/tmp/node_modules',
  '/private/node_modules',
  '/node_modules',
  '/usr/local/Cellar/node/11.11.0/lib/node_modules' ]
```

I previously installed the latest version of Node using Homebrew
```bash
$ which node
/usr/local/bin/node

$ readlink $(which node)
../Cellar/node/11.11.0/bin/node
```
The path that is is looking for is: `'/usr/local/Cellar/node/11.11.0/lib/node_modules'`

```bash
$ tree /usr/local/Cellar/node/11.11.0/lib
/usr/local/Cellar/node/11.11.0/lib
└── dtrace
    └── node.d

1 directory, 1 file
```

It looks like the Homebrew install and `npm` are out of sync.

```bash
$ which npm
/usr/local/bin/npm

$ readlink $(which npm)
../lib/node_modules/npm/bin/npm-cli.js
```

I never noticed this before because I try to install as few packages globally as possible.

I found the version of `npm` on my machine that was installed by Homebrew and created a new symlink to `/usr/local/bin/npm`, and now it works as intended. Thank you for writing good software.

I'd be happy to submit a PR to add a `Troubleshooting` section at the bottom of the `README` so that future people don't encounter the same problem if you would be interested in having that
